// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/joke.tsx";
import * as $5 from "./routes/api/login.ts";
import * as $6 from "./routes/api/post.ts";
import * as $7 from "./routes/api/register.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/login.tsx";
import * as $10 from "./routes/posts/[id]/edit.tsx";
import * as $11 from "./routes/posts/[id]/index.tsx";
import * as $12 from "./routes/posts/new.tsx";
import * as $13 from "./routes/signup.tsx";
import * as $14 from "./routes/task/index.tsx";
import * as $15 from "./routes/user/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LoginForm.tsx";
import * as $$2 from "./islands/PostForm.tsx";
import * as $$3 from "./islands/PostList.tsx";
import * as $$4 from "./islands/SignupForm.tsx";
import * as $$5 from "./islands/taskTodos.tsx";
import * as $$6 from "./islands/userTodos.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/joke.tsx": $4,
    "./routes/api/login.ts": $5,
    "./routes/api/post.ts": $6,
    "./routes/api/register.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/login.tsx": $9,
    "./routes/posts/[id]/edit.tsx": $10,
    "./routes/posts/[id]/index.tsx": $11,
    "./routes/posts/new.tsx": $12,
    "./routes/signup.tsx": $13,
    "./routes/task/index.tsx": $14,
    "./routes/user/index.tsx": $15,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LoginForm.tsx": $$1,
    "./islands/PostForm.tsx": $$2,
    "./islands/PostList.tsx": $$3,
    "./islands/SignupForm.tsx": $$4,
    "./islands/taskTodos.tsx": $$5,
    "./islands/userTodos.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
